[package]
name = "pkg_b"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.20.8"
rustls-pemfile = "1.0.2"
